### ISSUE TITLE
Please push new backports.inspect release to PyPI to fix setuptools incompatibility

### ISSUE THREAD

**Issue by jikamens** [agoraplex/backports.inspect#5]
backports.inspect 0.0.2 won't install with the newest setuptools because it depends on funcsigs 0.2, which is incompatible. However, the currenet backports.inspect trunk uses funcsigs 0.4, which is compatible with the current setuptools. Please push an update to PyPI.

Thanks.

**Comment by msabramo** [comment]
Just released https://pypi.python.org/pypi/backports.inspect/0.0.3 to PyPI; can you please confirm that this solves the problem you were experiencing?

**Comment by jikamens** [comment]
Looks good, thanks.

**Comment by msabramo** [comment]
Awesome! Thanks for checking!
